### ISSUE TITLE
Observer function example

### ISSUE THREAD

**Issue by VolkerH** [hammerlab/flowdec#9]
Hi, 

first of all thank you for this awesome library. I started experimenting with it a couple of days ago and am getting excellent results. 

Now my issue: I'm trying to use the observer function to write intermediate iteration results to disk (I would like to see how the iterations progress) during deconvolution. There is no documentation on this, so a working example would be greatly appreciated. My own attempts were unsuccessful so far (defining some minimalist observer function).

```
#define an observer function
def observer(*arg):
    print("Observer called")

# Direct deconvolution on skewed llsm dataset
spimrawvol = tifffile.imread("/home/vhil0002/test_vol.tif")
spimskewpsf = tifffile.imread("/home/vhil0002/test_skewed_psf.tif")

algo_skew = tfd_restoration.RichardsonLucyDeconvolver(n_dims=3, start_mode='input', observer_fn=observer).initialize()
aq_skew = fd_data.Acquisition(data=spimrawvol.astype(np.float32), kernel=spimskewpsf.astype(np.float32))
res_skew = algo_skew.run(aq_skew, niter=3)
``` 

I can see that it gets called once and then I get an exception (probably when it returns) with a lengthy traceback. I've tried returning integers (32 and 64 bit) from the observer or just returning all the input arguments but get pretty much the same error no matter what.

```
Observer called

---------------------------------------------------------------------------
InvalidArgumentError                      Traceback (most recent call last)
~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1333     try:
-> 1334       return fn(*args)
   1335     except errors.OpError as e:

~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1318       return self._call_tf_sessionrun(
-> 1319           options, feed_dict, fetch_list, target_list, run_metadata)
   1320 

~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1406         self._session, options, feed_dict, fetch_list, target_list,
-> 1407         run_metadata)
   1408 

InvalidArgumentError: 0-th value returned by pyfunc_6 is int64, but expects int32
	 [[{{node while/observer}} = PyFunc[Tin=[DT_FLOAT, DT_INT32], Tout=[DT_INT32], token="pyfunc_6", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/Maximum/_85, while/Identity/_87)]]

During handling of the above exception, another exception occurred:

InvalidArgumentError                      Traceback (most recent call last)
<ipython-input-37-007b7300fa24> in <module>
     12 
     13  #   %%timeit
---> 14 res_skew = algo_skew.run(aq_skew, niter=3)

~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/restoration.py in run(self, acquisition, niter, session_config)
    211     def run(self, acquisition, niter, session_config=None):
    212         input_kwargs = dict(niter=niter, pad_mode=self.pad_mode, pad_min=self.pad_min, start_mode=self.start_mode)
--> 213         res = self._run(acquisition, input_kwargs, session_config=session_config)
    214         return DeconvolutionResult(res['result'], info={k: v for k, v in res.items() if k != 'result'})
    215 

~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/restoration.py in _run(self, acquisition, input_kwargs, session_config)
     81             data_dict = {self.graph.inputs[k]:v for k, v in acquisition.to_feed_dict().items()}
     82             args_dict = {self.graph.inputs[k]:v for k, v in input_kwargs.items() if v is not None}
---> 83             res = sess.run(self.graph.outputs, feed_dict={**data_dict, **args_dict})
     84             return res
     85 

~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    927     try:
    928       result = self._run(None, fetches, feed_dict, options_ptr,
--> 929                          run_metadata_ptr)
    930       if run_metadata:
    931         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1150     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1151       results = self._do_run(handle, final_targets, final_fetches,
-> 1152                              feed_dict_tensor, options, run_metadata)
   1153     else:
   1154       results = []

~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1326     if handle is None:
   1327       return self._do_call(_run_fn, feeds, fetches, targets, options,
-> 1328                            run_metadata)
   1329     else:
   1330       return self._do_call(_prun_fn, handle, feeds, fetches)

~/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1346           pass
   1347       message = error_interpolation.interpolate(message, self._graph)
-> 1348       raise type(e)(node_def, op, message)
   1349 
   1350   def _extend_graph(self):

InvalidArgumentError: 0-th value returned by pyfunc_6 is int64, but expects int32
	 [[node while/observer (defined at /home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/tf_ops.py:31)  = PyFunc[Tin=[DT_FLOAT, DT_INT32], Tout=[DT_INT32], token="pyfunc_6", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/Maximum/_85, while/Identity/_87)]]

Caused by op 'while/observer', defined at:
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/ipykernel/kernelapp.py", line 505, in start
    self.io_loop.start()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/asyncio/base_events.py", line 427, in run_forever
    self._run_once()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/asyncio/base_events.py", line 1440, in _run_once
    handle._run()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/asyncio/events.py", line 145, in _run
    self._callback(*self._args)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tornado/gen.py", line 1233, in inner
    self.run()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tornado/gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 357, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 267, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/ipykernel/kernelbase.py", line 534, in execute_request
    user_expressions, allow_stdin,
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/ipykernel/ipkernel.py", line 294, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2819, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 2845, in _run_cell
    return runner(coro)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/IPython/core/async_helpers.py", line 67, in _pseudo_sync_runner
    coro.send(None)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3020, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3185, in run_ast_nodes
    if (yield from self.run_code(code, result)):
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-37-007b7300fa24>", line 9, in <module>
    algo_skew = tfd_restoration.RichardsonLucyDeconvolver(n_dims=3, start_mode='input', observer_fn=observer).initialize()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/restoration.py", line 62, in initialize
    self.graph = self._get_tf_graph()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/restoration.py", line 58, in _get_tf_graph
    inputs, outputs = self._build_tf_graph()
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/restoration.py", line 308, in _build_tf_graph
    result = tf.while_loop(cond, body, [1, decon], parallel_iterations=1)[1]
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3291, in while_loop
    return_same_structure)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 3004, in BuildLoop
    pred, body, original_loop_vars, loop_vars, shape_invariants)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/ops/control_flow_ops.py", line 2939, in _BuildLoop
    body_result = body(*packed_vars_for_body)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/restoration.py", line 304, in body
    decon, i = tf_observer([decon, i], self.observer_fn)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/tf_ops.py", line 31, in tf_observer
    observe_op = tf.py_func(_observe, tensors, tf.int32, stateful=True, name='observer')[0]
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 457, in py_func
    func=func, inp=inp, Tout=Tout, stateful=stateful, eager=False, name=name)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/ops/script_ops.py", line 281, in _internal_py_func
    input=inp, token=token, Tout=Tout, name=name)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/ops/gen_script_ops.py", line 129, in py_func
    "PyFunc", input=input, token=token, Tout=Tout, name=name)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

InvalidArgumentError (see above for traceback): 0-th value returned by pyfunc_6 is int64, but expects int32
	 [[node while/observer (defined at /home/vhil0002/su62_scratch/volker_conda/llsm/lib/python3.6/site-packages/flowdec/tf_ops.py:31)  = PyFunc[Tin=[DT_FLOAT, DT_INT32], Tout=[DT_INT32], token="pyfunc_6", _device="/job:localhost/replica:0/task:0/device:CPU:0"](while/Maximum/_85, while/Identity/_87)]]

```

**Comment by eric-czech** [comment]
Hey @VolkerH ,

This should be all set now.  Thanks for outlining the problem well and to avoid this for any future users, I added a related [Example Notebook](https://github.com/hammerlab/flowdec/blob/3b7fdb9d2cd29b62e7e97142353ec76408dc44b5/python/examples/notebooks/Monitoring%20Iterations.ipynb), a unit test for observer functions, and updated the doc string to explain what the signature should be.

Here's a short self-contained example:

```python
from flowdec import data as fd_data
from flowdec import restoration as fd_restoration
imgs = []

def observer(img, i, *args):
    # img: float32 array containing current state of deconvolved image
    # i: 1-based iteration counter
    imgs.append(img)
    if i % 10 == 0:
        print('Observing iteration', i)

acq = fd_data.bars_25pct()
algo = fd_restoration.RichardsonLucyDeconvolver(n_dims=3, observer_fn=observer)
algo.initialize().run(acq, niter=100)
assert len(imgs) == 100
```

I'll close this out for now but let me know if you run into issues with that again.

**Comment by VolkerH** [comment]
Thanks a lot for the quick fix @eric-czech 
I won't get to try before Tuesday due to other commitments. Will report back.

**Comment by VolkerH** [comment]
Thanks again, just tested it. Works for me.

**Comment by eric-czech** [comment]
Excellent --  feel free to post any other issues or feature requests you might have @VolkerH and thanks for the update!
